---
- name: Setup Docker-Server
  hosts: localhost
  remote_user: root

  tasks:

  - name: Hello Server
    debug:
      msg: "Hello mein guter Mensch!" 
      
  - name: Touch a file, using symbolic modes to set the permissions (equivalent to 0644)
    file:
      path: /etc/foo.conf
      state: touch
      mode: u=rw,g=r,o=r
      
  - name: Ausgabe mit Variablen
    debug:
      msg: "{{ mein_cooler_text }}" 
